Classification algorithms on Placement class dataset

In [443]:
# Import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [444]:
#Load dataset
dataset = pd.read_csv('datasets\Placement_Data_Full_Class.csv')

In [445]:
dataset

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

## Preprocessing of the dataset

In [446]:
dataset = dataset.drop(labels=['sl_no', 'salary'], axis=1)

**Seperating features and target**

In [447]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [448]:
X

array([['M', 67.0, 'Others', ..., 55.0, 'Mkt&HR', 58.8],
       ['M', 79.33, 'Central', ..., 86.5, 'Mkt&Fin', 66.28],
       ['M', 65.0, 'Central', ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       ['M', 67.0, 'Others', ..., 59.0, 'Mkt&Fin', 69.72],
       ['F', 74.0, 'Others', ..., 70.0, 'Mkt&HR', 60.23],
       ['M', 62.0, 'Central', ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [449]:
y

array(['Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
  

**Encoding the textual information**

In [450]:
from sklearn.preprocessing import LabelEncoder

In [451]:
le = LabelEncoder()

In [452]:
X[:, 0] = le.fit_transform(X[:, 0]) # gender field
X[:, 2] = le.fit_transform(X[:, 2]) # ssc_b field
X[:, 4] = le.fit_transform(X[:, 4]) # hsc_b field
X[:, 5] = le.fit_transform(X[:, 5]) # hsc_s field
X[:, 7] = le.fit_transform(X[:, 7]) # degree_t field
X[:, 8] = le.fit_transform(X[:, 8]) # workex field
X[:, 10] = le.fit_transform(X[:, 10]) # specialisation field

In [453]:
X[1:2, :]

array([[1, 79.33, 0, 78.33, 1, 2, 77.48, 2, 1, 86.5, 0, 66.28]],
      dtype=object)

**Splitting the dataset in to train set and test set**

In [454]:
from sklearn.model_selection import train_test_split

In [455]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [456]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

172
43
172
43


**Scaling the dataset**

In [457]:
from sklearn.preprocessing import StandardScaler

In [458]:
sc = StandardScaler()

In [459]:
X_train = sc.fit_transform(X_train)

In [460]:
X_test = sc.transform(X_test)

**Since the target has discrete values Classification Machine Learning algorithms will be employed**

## Logistic Regression

In [461]:
from sklearn.linear_model import LogisticRegression

**Training the model**

In [462]:
lclf = LogisticRegression(max_iter=1000)

In [463]:
lclf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

**Performing predictions on test set**

In [464]:
lpred = lclf.predict(X_test)

In [465]:
lpred

array(['Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Placed', 'Placed'], dtype=object)

**Metrics of the algorithm**

In [466]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [467]:
print("Confusion Matrix: \n", confusion_matrix(y_test, lpred))

Confusion Matrix: 
 [[12  7]
 [ 2 22]]


In [468]:
print("Accuracy Score : ", accuracy_score(y_test, lpred))

Accuracy Score :  0.7906976744186046


## Decision Tree Classification

In [469]:
from sklearn.tree import DecisionTreeClassifier

**Training the model**

In [470]:
dclf = DecisionTreeClassifier()

In [471]:
dclf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

**Performing predictions on test set**

In [472]:
dpred = dclf.predict(X_test)

In [473]:
dpred

array(['Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Not Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed'], dtype=object)

**Metrics of the algorithm**

In [474]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [475]:
print("Confusion Matrix : \n", confusion_matrix(y_test, dpred))

Confusion Matrix : 
 [[11  8]
 [ 2 22]]


In [476]:
print("Accuracy Score : ", accuracy_score(y_test, dpred))

Accuracy Score :  0.7674418604651163


## K Nearest Neighbours Classification

In [477]:
from sklearn.neighbors import KNeighborsClassifier

**Training the model**

In [478]:
knnclf = KNeighborsClassifier(n_neighbors=5)

In [479]:
knnclf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

**Performing predictions on test set**

In [480]:
knnpred = knnclf.predict(X_test)

In [481]:
knnpred

array(['Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Not Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Placed', 'Placed', 'Placed'], dtype=object)

**Metrics of the algorithm**

In [482]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [483]:
print("Confusion Matrix : \n", confusion_matrix(y_test, knnpred))

Confusion Matrix : 
 [[13  6]
 [ 2 22]]


In [484]:
print("Accuracy Score : ", accuracy_score(y_test, knnpred))

Accuracy Score :  0.813953488372093


## Random Forest Classification

In [485]:
from sklearn.ensemble import RandomForestClassifier

**Training the model**

In [486]:
rclf = RandomForestClassifier(n_estimators=100)

In [487]:
rclf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

**Performing predictions on test set**

In [488]:
rpred = rclf.predict(X_test)

In [489]:
rpred

array(['Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Placed', 'Placed'], dtype=object)

**Metrics of the algorithm**

In [490]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [491]:
print("Confusion Matrix : \n", confusion_matrix(y_test, rpred))

Confusion Matrix : 
 [[12  7]
 [ 0 24]]


In [492]:
print("Accuracy Score : ", accuracy_score(y_test, rpred))

Accuracy Score :  0.8372093023255814


## Support Vector Machine Classification

In [493]:
from sklearn.svm import SVC

**Training the model (SVC linear kernel)**

In [494]:
svc_linearclf = SVC(kernel='linear')

In [495]:
svc_linearclf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

**Training the model (SVC rbf kernel)**

In [496]:
svc_rbfclf = SVC(kernel='rbf')

In [497]:
svc_rbfclf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

**Performing predictions on test set(SVC linear kernel)**

In [498]:
svc_linear_pred = svc_linearclf.predict(X_test)

In [499]:
svc_linear_pred

array(['Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Placed', 'Placed'], dtype=object)

**Performing predictions on test set(SVC rbf kernel)**

In [500]:
svc_rbf_pred = svc_rbfclf.predict(X_test)

In [501]:
svc_rbf_pred

array(['Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed',
       'Placed', 'Placed', 'Placed'], dtype=object)

**Metrics of the algorithm (SVC linear kernel)**

In [502]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [503]:
print("Confusion Matrix : \n", confusion_matrix(y_test, svc_linear_pred))

Confusion Matrix : 
 [[12  7]
 [ 1 23]]


In [504]:
print("Accuracy Score : ", accuracy_score(y_test, svc_linear_pred))

Accuracy Score :  0.813953488372093


**Metrics of the algorithm (SVC rbf kernel)**

In [505]:
print("Confusion Matrix : \n", confusion_matrix(y_test, svc_rbf_pred))

Confusion Matrix : 
 [[13  6]
 [ 0 24]]


In [506]:
print("Accuracy Score : ", accuracy_score(y_test, svc_rbf_pred))

Accuracy Score :  0.8604651162790697


## Conclusion

**Support Vector Machine Classification(RBF Kernel) has the highest accuracy score compared to other Classifcation models for the given Placement Data Full Class dataset.Hence Support Vector Machine Classification is the best model for Classification problems**